### ISSUE TITLE
Send notification to user after each client deploy

### ISSUE THREAD

**Issue by joelmoss** [codio/Issues#1]
Currently when the client is deployed, users are not aware of it unless something breaks due to incompatibilities between the old client that they currently use, and the rest of the system (server, sharejs, etc.).

We should show a notification to let them know they have an old version, and that they should reload the page to get up to date.

Thoughts on how to do this?

**Comment by dignifiedquire** [comment]
We could use the the socket connection to sharejs, add a duplex stream on it and communicate the client version checking if it's the latest and if not show a blocker asking the user to reload.

**Comment by joelmoss** [comment]
Should it be a blocker or just a notice?

**Comment by dignifiedquire** [comment]
what ever we like

**Comment by joelmoss** [comment]
Closed in favour of codio/client#2407
