### ISSUE TITLE
code suggestion

### ISSUE THREAD

**Issue by escuriola** [codio/Issues#12]
It will be nice to have the suggestion to php functions and own project functions.

It's not an issue but an improvement but I have a large project and it's more difficult to work without suggestions... 

Thanks

**Comment by nesl247** [comment]
What you are asking for is Intellisense, and it's definitely something that is a MUST have.

**Comment by ksimuk** [comment]
We are working on Intellisense for javascript now, first version will be available soon.

**Comment by escuriola** [comment]
Great. I'm seriously thinking in purchase an account. Great work!

Regards.

On Mon, Mar 3, 2014 at 4:50 PM, Maxim Kraev notifications@github.comwrote:

> We are working on Intellisense for javascript now, first version will be
> available soon.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/codio/Issues/issues/12#issuecomment-36523107
> .

## 

Carlos Escuriola Marín

**Comment by nesl247** [comment]
@MaximKraev True Intellisense as in it will read JSDoc, read our own custom functions scattered in any file, etc., and show tooltips on proper usage as we type?

**Comment by ksimuk** [comment]
Intellisense is based on  http://ternjs.net library.
the first release is just code complete, but in plans we are going to have:
- on refactoring/rename
- full project support
- jump to definition
- show function arguments and variables types 
  the first version is looks like:
  ![intellisense](https://f.cloud.github.com/assets/575940/2312115/df3146d8-a2f7-11e3-967d-1c0df56351f6.png)

**Comment by nesl247** [comment]
Looking forward to it. More so when you guys add Intellisense for PHP.

**Comment by ksimuk** [comment]
was deployed
