### ISSUE TITLE
Terminal content past breakpoint

### ISSUE THREAD

**Issue by nesl247** [codio/Issues#13]
Wasn't sure how to title this best. The issue where the content of the terminal becomes hidden because it expands past the actual terminal box is back or was never 100% fixed.

I was able to replicate this by doing `git status` twice when I had enough content, or doing a `cat`, or anything else that outputs enough lines.

Testing this on IE 11 (Metro) on Win 8.1. This is not reproducible on Chrome.

**Comment by VeronikaLee** [comment]
@nesl247 this bug is fixed, can you approve that terminal works correct for you? Thank you.
