### ISSUE TITLE
SSH Connections Manager forgets saved connections

### ISSUE THREAD

**Issue by 99hats** [codio/Issues#14]
I can save my connections fine and they show up on the list of SSH connections. When I close the window and re-open  tools > ssh > Connections Manager all of my saved connections are gone. Instead I see the create connection form.

**Comment by ghost** [comment]
Hi,
Could you show the steps you are taking in settings up, saving and then re accessing the Connections Manager in a video with your dev console open so we can try to see what is occurring here for you. 

If you don't have any capture software Jing is good for doing this and you can get Jing from <a href="http://www.techsmith.com/jing.html">here</a>. Once you have recorded, please make sure you upload the video to screencast and post the link

**Comment by 99hats** [comment]
Hi,

Thanks for looking into this.

http://screencast.com/t/t54I7MWmyM

It might be just my home machine. I tried it one other place and it worked as expected, however if I then open it in my home machine, it erases it.

**Comment by ghost** [comment]
Hi..
Can you see if there are any errors showing in  the dev console when you set up , then close and re open the connections manager? 

Also what OS and browser are you seeing this on (I think you are using Chrome from the screencast but not sure on the OS)
