### ISSUE TITLE
Files never end loading ... Tabs gone... 

### ISSUE THREAD

**Issue by mmmattos** [codio/Issues#17]
Hi Joel,

I have this public repo with the Restful API demo based on ExpressJS and Node.
It was ok until yesterday. As of now files (.js, .sh, for instance) never end loading in  the IDE... There is a .txt file that loads fast, but for others the progress bar goes forever.

I checked in other project (private) and it happens too.... 

At first I thought it could with some data files but that´s not the case.
Also while these files never end loading the Tabs at the top (to access other files) are simply gone... 

Regards,
Miguel.

**Comment by joelmoss** [comment]
So sorry, but all is now running as normal. We are monitoring things very closely now, but please let me know if you experience any further issues.

FYI, we have a status page at http://status.codio.com

**Comment by mmmattos** [comment]
Thanks Joel..! I´ll let you know if it happens again.

## Regards,

_MIGUEL MIRANDA DE MATTOS_
_Cel. (51) 9198 9914_
http://linkedin.com/in/miguelmirandademattos/
about.me/mmmattos
