### ISSUE TITLE
Percentage (%) read

### ISSUE THREAD

**Issue by nblackburn** [codio/Issues#18]
I am not entirely sure how this works so please correct me if I am wrong but as far as I am aware, it reflects the percentage though the document you are currently at. If i am correct with my asumption then it appears to be very broken.
#### Example

I have a single line file that requires the base module for the project I am working on but the percentage reflects at `0%` on line one of one when it should be `100%`. It is only possible to get to `100%` when the document is `101` or more lines long.

**Comment by ghost** [comment]
good spot, hadn't noticed that, but sorted and update pushed so you should now see 100% at the bottom of all files. 
Check it out and let is know if you see anything wrong

**Comment by nblackburn** [comment]
Seems to be working beautifully, good job! :)
