### ISSUE TITLE
CSS font loading now bug due to version

### ISSUE THREAD

**Issue by hugolpz** [codio/Issues#20]
The popular [FontAwesome.css](http://fortawesome.github.io/Font-Awesome/) was working fine, and started to bug about September 15-17th, not displaying the relevant font-icons. I found the issue. 

---

**Before Sept 15-17th**,  `font-awesome.css` was working fine with : 

```
 url('../fonts/fontawesome-webfont.ttf?v=4.2.0') format('truetype'),
```

![works](https://cloud.githubusercontent.com/assets/1420189/4332213/f1e65d2e-3fd0-11e4-86ca-1ad99d90b275.png)

---

**After Sept 15-17th**, `font-awesome.css` same code fails, the `v=4.2.0` cause the failure: 
![working-not](https://cloud.githubusercontent.com/assets/1420189/4332235/36590498-3fd1-11e4-95a1-3b2c1d3a9f5a.png)

And the following code (without `?v=4.2.0`) works:

```
 url('../fonts/fontawesome-webfont.ttf') format('truetype'),
```

![works](https://cloud.githubusercontent.com/assets/1420189/4332213/f1e65d2e-3fd0-11e4-86ca-1ad99d90b275.png)

**Yet, why does the version now breaks my code ? Since this `?v=4.2.0` still works on  [FontAwesome website](http://fortawesome.github.io/Font-Awesome/), it may be due to Codio itself...**

Tested with Chromium Version 37.0.2062.94 Ubuntu 14.04 (290621) (64-bit) on [this project](http://prison-lavage.codio.io/pages/next.html) / css / [font-awesome.css](http://prison-lavage.codio.io/css/font-awesome.css)

**Comment by hugolpz** [comment]
Add: 
- https://prison-lavage.codio.io/fonts/fontawesome-webfont.woff?v=4.2.0 dowload **fails**.
- https://prison-lavage.codio.io/fonts/fontawesome-webfont.woff download works.

Codio servers settings ?

**Comment by joelmoss** [comment]
We're looking into this now and will get back to you ASAP.

**Comment by hugolpz** [comment]
Chrome console. 

![chrome console](https://cloud.githubusercontent.com/assets/1420189/4334127/c471d3e6-3fe9-11e4-8cc2-45b8270ad7c0.png)

Thanks Joel.

**Comment by joelmoss** [comment]
Please try now as all should be working fine now.

**Comment by hugolpz** [comment]
Fixed for me ! Thanks you.
Note: was my diagnostic correct and helpful ? (I' am still learning around)

**Comment by joelmoss** [comment]
yes it was very helpful, thx
