### ISSUE TITLE
Info on the inotify events raised by Codio IDE

### ISSUE THREAD

**Issue by clupasq** [codio/Issues#26]
I'm trying to use a tool named [Guard](https://github.com/guard/guard) to automatically run some ruby tests, when the source files are modified.

For some reason, this does not work when I modify the files with the Codio text editor. When I modify the files in the terminal using vim, it works fine.

Guard uses inotify events to detect when files have been modified. One of the guys responsible for the project helped me diagnose this issue and we have reached a point where we need to know either:
- whether it's possible to alter the behavior of the Text Editor to raise the expected events

or
- whether the events triggered by the Codio Text Editor in different scenarios are documented somewhere, so that Guard could be adjusted to support it

Here's another issue on the topic: https://github.com/guard/listen/issues/287

Thanks!

**Comment by ksimuk** [comment]
UPD.

We are writing a file content to a temporary buffer file and as soon as all content is written, we move temporary file to the original place. inotify should work. 

And I see with debug flag guard performs actions on file changes from codio, just do not trigger an update for some reason.

**Comment by ksimuk** [comment]
the fix released. thank you for your feedback.

**Comment by clupasq** [comment]
You guys are awesome! Codio rocks!
