### ISSUE TITLE
Improved notifications

### ISSUE THREAD

**Issue by dignifiedquire** [codio/Issues#3]
At the moment the notifications are design wise very unfitting to the rest of the interface and the block too much screen. I think we should move to something like growl with notifications in the upper right hand corner:

![multipledisplays](https://f.cloud.github.com/assets/790842/2196990/0faf97c4-98b7-11e3-98cc-94d6b3fc9acc.png)

**Comment by joelmoss** [comment]
They are just as unfitting and even larger in some ways. We could think about using Chrome's notifications.

**Comment by joelmoss** [comment]
I like http://github.hubspot.com/messenger/

**Comment by AnnaGlushkova** [comment]
forum post - http://forum.codio.com/t/move-deployment-notifications-out-of-editor-pane/433/

**Comment by dignifiedquire** [comment]
> I like http://github.hubspot.com/messenger/

looks great

**Comment by dignifiedquire** [comment]
> They are just as unfitting and even larger in some ways. We could think about using Chrome's notifications.

We can't use growl in the browser so that was just to illustrate what I had in mind.

**Comment by joelmoss** [comment]
If we don't want them overlaying anything, the trick is to find out where to put them, and taking different types of notices into consideration. For example, errors, and info messages.
