### ISSUE TITLE
Bower should be installed by default

### ISSUE THREAD

**Issue by nesl247** [codio/Issues#4]
Bower should be part of the system itself (not a box part, hence me putting this here instead). It's usable through the IDE itself, but not through the terminal by default. It should be in both places.

**Comment by joelmoss** [comment]
Nice idea, but it's so easy to install grunt, that I don't think it is needed to be installed by default. We also need to be careful about what we install by default, as the more we have, the more we have to manage, maintain, etc.

**Comment by dignifiedquire** [comment]
I have to agree with @nesl247 that `bower` should be an exception as it is usable through the IDE.
