### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by fmay** [codio/Issues#6]
This project : https://codio.com/steganographer/JS-PenGO-io

The user clicks the "Preview->Project Index (static)" it opens a page to "http://null.codio.io" which has nothing on it...

See this Intercom issue : https://www.intercom.io/apps/ee8711023afa04b80a6b921ddb3939c1171e0f62/messages/1231846/message_threads/1585266

**Comment by fmay** [comment]
Apparently, once the migration process is finished, this error should disappear. All migrations should be finished within the next 6 hours.

**Comment by AnnaGlushkova** [comment]
the migration process is done and all should work.
recheck please and let us know if you still have preview URL like "http://null.codio.io"

**Comment by fmay** [comment]
yes, works
